language: go

go:
  - 1.11.x

before_script:
  - go fmt ./...
  - go vet ./...
  - go test -coverprofile=c.out

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh 

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - dep ensure

