language: go

go:
  - 1.12.x

before_script:
  - go fmt ./...
  - go vet ./...
  - go test -v -race -coverpkg=github.com/cbush06/kosher/... -covermode=atomic -coverprofile=coverage.txt github.com/cbush06/kosher/... 

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh 

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - dep ensure

after_success:
  - bash <(curl -s https://codecov.io/bash)
