language: go

go:
  - 1.11.x

before_script:
  - go vet ./...

before_install:
  - sudo apt-get install go-dep

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - dep ensure

