
[[constraint]]
  name = "github.com/sclevine/agouti"
  version = "3.0.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.13"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.9.0"