title: kosher2
description: Web driver wrapper written in Golang that empowers non-developers to functionally test web applications using simple Gherkin scripts.
url: "https://cbush06.github.io"
baseurl: "kosher"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links: "kosher on GitHub:"
  - "https://github.com/cbush06/kosher"
